import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import process from 'node:process';
const { chromium } = createRequire(import.meta.url)('playwright');
const base = process.env.BIBLE_TEST_URL || 'http://127.0.0.1:5181';
const output = 'test-results/bible-experience';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const errors = [];
async function scrollToVerse(regions, index, verse) {
  await regions.nth(index).evaluate((element, number) => {
    const anchor = [...element.querySelectorAll('.bible-verse-start')].find(node => node.dataset.reference.split('+').some(ref => Number(ref.split('.').at(-1)) === number));
    element.scrollTop += anchor.getBoundingClientRect().top - element.getBoundingClientRect().top + 3;
  }, verse);
}
async function assertSynced(page, verse) {
  await page.waitForFunction(number => [...document.querySelectorAll('.bible-compare-scroll')].every(element => {
    const origin = element.getBoundingClientRect().top;
    const anchors = [...element.querySelectorAll('.bible-verse-start')];
    const anchor = anchors.filter(node => node.getBoundingClientRect().top <= origin + 1).at(-1) || anchors[0];
    return anchor?.dataset.reference.split('+').some(ref => Number(ref.split('.').at(-1)) === number);
  }), verse);
}
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', permissions: ['clipboard-read', 'clipboard-write'] });
  await context.route('https://**/*', route => route.abort());
  const page = await context.newPage();
  page.setDefaultTimeout(15000);
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}/biblia`);
  await page.getByLabel('Opciones del versículo GEN.1.1', { exact: true }).waitFor();
  const first = await page.locator('.bible-verse-start[data-reference="GEN.1.1"]').boundingBox();
  const second = await page.locator('.bible-verse-start[data-reference="GEN.1.2"]').boundingBox();
  assert.ok(second.y >= first.y + first.height, 'Verses must occupy separate lines');
  await page.locator('.bible-verse-start[data-reference="GEN.1.1"]').click({ position: { x: 60, y: 15 } });
  assert.equal(await page.getByRole('dialog').count(), 0);
  assert.equal(await page.locator('.bible-verse-selected[data-reference="GEN.1.1"]').count(), 1);
  await page.getByRole('button', { name: 'Guardar favorito', exact: true }).click();
  await page.getByRole('button', { name: 'Copiar versículo', exact: true }).click();
  await page.getByText('Versículo copiado con su referencia.').waitFor();
  assert.equal((await page.evaluate(() => navigator.clipboard.readText())).replace(/\r\n/g, '\n'), 'Génesis 1:1 (RVR1960)\n\n«En el principio creó Dios los cielos y la tierra.»');
  await page.screenshot({ path: `${output}/verse-actions.png` });
  await page.getByLabel('Cerrar selección').click();
  await page.reload();
  await page.getByLabel('Marcadores', { exact: true }).click();
  await page.getByRole('tab', { name: /Versículos/ }).click();
  assert.match(await page.getByRole('tabpanel').innerText(), /Génesis 1:1 \(RVR1960\)/);
  await page.locator('.bible-favorite-row > button').first().click();
  await page.locator('.bible-verse-selected[data-reference="GEN.1.1"]').waitFor();
  await page.getByLabel('Comparar versiones', { exact: true }).click();
  assert.equal(await page.getByRole('checkbox').count(), 4);
  assert.equal(await page.getByRole('checkbox').last().isDisabled(), true);
  await page.getByRole('button', { name: 'Comparar', exact: true }).click();
  await page.getByRole('region', { name: 'Lectura NVI', exact: true }).locator('.bible-verse-action').first().waitFor();
  const regions = page.locator('.bible-compare-scroll');
  assert.equal(await regions.count(), 3);
  await scrollToVerse(regions, 0, 31);
  await assertSynced(page, 31);
  await scrollToVerse(regions, 0, 8);
  await assertSynced(page, 8);
  await scrollToVerse(regions, 1, 12);
  await assertSynced(page, 12);
  await page.screenshot({ path: `${output}/compare-desktop.png` });
  await regions.nth(1).hover();
  const beforeWheel = await regions.evaluateAll(elements => elements.map(element => element.scrollTop));
  await page.mouse.wheel(0, 240);
  await page.waitForFunction(previous => [...document.querySelectorAll('.bible-compare-scroll')].every((element, index) => element.scrollTop > previous[index]), beforeWheel);
  await regions.nth(2).focus();
  const beforeKey = await regions.evaluateAll(elements => elements.map(element => element.scrollTop));
  await page.keyboard.press('PageDown');
  await page.waitForFunction(previous => [...document.querySelectorAll('.bible-compare-scroll')].every((element, index) => element.scrollTop > previous[index]), beforeKey);
  await scrollToVerse(regions, 2, 1);
  await page.getByRole('region', { name: 'Lectura NVI', exact: true }).getByLabel('Opciones del versículo GEN.1.1', { exact: true }).click();
  assert.match(await page.getByRole('region', { name: 'Versículo seleccionado', exact: true }).innerText(), /Génesis 1:1 \(NVI\)/);
  assert.equal(await page.getByRole('region', { name: 'Lectura RVR1960', exact: true }).locator('.bible-verse-selected').count(), 0);
  await page.getByRole('button', { name: 'Guardar favorito', exact: true }).click();
  await page.getByLabel('Cerrar selección').click();
  for (const width of [320, 390, 768]) {
    await page.setViewportSize({ width, height: 844 });
    const lineRatio = await regions.first().evaluate(element => {
      const style = getComputedStyle(element); return parseFloat(style.lineHeight) / parseFloat(style.fontSize);
    });
    assert.ok(Math.abs(lineRatio - (width < 768 ? 1.5 : 1.65)) < 0.01);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${width}`);
    const boxes = await page.locator('.bible-compare-column').evaluateAll(elements => elements.map(element => {
      const { x, y, width, height } = element.getBoundingClientRect(); return { x, y, width, height };
    }));
    assert.ok(boxes.every(box => box.height > 150 && box.x >= 0 && box.x + box.width <= width && box.y + box.height <= 844));
    assert.ok(boxes[1].y >= boxes[0].y + boxes[0].height - 1 && boxes[2].y >= boxes[1].y + boxes[1].height - 1);
    await scrollToVerse(regions, 2, 8);
    await assertSynced(page, 8);
    await scrollToVerse(regions, 1, 15);
    await assertSynced(page, 15);
    await page.screenshot({ path: `${output}/compare-${width}.png` });
  }
  await page.setViewportSize({ width: 320, height: 568 });
  await scrollToVerse(regions, 0, 31);
  await assertSynced(page, 31);
  await page.screenshot({ path: `${output}/compare-short.png` });
  await page.getByLabel('Comparar versiones', { exact: true }).click();
  await page.getByRole('checkbox', { name: /NVI/ }).uncheck();
  await page.getByRole('button', { name: 'Comparar', exact: true }).click();
  assert.equal(await regions.count(), 2);
  await scrollToVerse(regions, 1, 8);
  await assertSynced(page, 8);
  await page.screenshot({ path: `${output}/compare-two-mobile.png` });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await assertSynced(page, 8);
  await page.screenshot({ path: `${output}/compare-two-desktop.png` });
  await page.getByLabel('Comparar versiones', { exact: true }).click();
  await page.getByRole('checkbox', { name: /NVI/ }).check();
  await page.getByRole('button', { name: 'Comparar', exact: true }).click();
  await page.getByRole('button', { name: 'Siguiente', exact: true }).click();
  await page.getByRole('region', { name: 'Lectura NVI', exact: true }).locator('.bible-verse-action').first().waitFor();
  assert.deepEqual(await regions.evaluateAll(elements => elements.map(element => element.scrollTop)), [0, 0, 0]);
  assert.ok((await page.locator('.bible-compare-column > header').allTextContents()).every(text => text.includes('2')));
  await page.getByLabel('Comparar versiones', { exact: true }).click();
  await page.getByRole('checkbox', { name: /NVI/ }).uncheck();
  await page.getByRole('checkbox', { name: /TLA/ }).check();
  await page.getByRole('button', { name: 'Comparar', exact: true }).click();
  await page.getByRole('region', { name: 'Lectura TLA', exact: true }).locator('.bible-verse-action').first().waitFor();
  await scrollToVerse(regions, 0, 2);
  await assertSynced(page, 2);
  await scrollToVerse(regions, 2, 8);
  await assertSynced(page, 8);
  await page.getByLabel('Ajustes de lectura').click();
  await page.getByLabel('Aumentar texto').click();
  await page.getByLabel('Tema claro').click();
  await page.getByRole('dialog').getByLabel('Cerrar ventana').click();
  await assertSynced(page, 8);
  await page.setViewportSize({ width: 390, height: 844 });
  await assertSynced(page, 8);
  await page.screenshot({ path: `${output}/compare-light-grouped.png` });
  await page.getByLabel('Cerrar comparación').click();
  await page.getByLabel('Marcadores', { exact: true }).click();
  assert.equal(await page.locator('.bible-favorite-row').count(), 2);
  await page.getByLabel('Eliminar favorito Génesis 1:1 (NVI)', { exact: true }).click();
  assert.equal(await page.locator('.bible-favorite-row').count(), 1);
  await page.getByRole('dialog').getByLabel('Cerrar ventana').click();
  // Permission denial must provide selectable text instead of claiming a successful copy.
  await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw new DOMException('Denied', 'NotAllowedError'); }; });
  await page.locator('.bible-verse-action').first().click();
  await page.getByRole('button', { name: 'Copiar versículo', exact: true }).click();
  await page.getByLabel('Texto para copiar').waitFor();
  assert.ok((await page.getByLabel('Texto para copiar').inputValue()).includes('(RVR1960)'));
  await page.getByLabel('Cerrar selección').click();
  // Storage failure must not pretend that a favorite was persisted.
  await page.evaluate(() => { const original = Storage.prototype.setItem; Storage.prototype.setItem = function (key, value) { if (key === 'bible:verseFavorites') throw new DOMException('Full', 'QuotaExceededError'); return original.call(this, key, value); }; });
  await page.locator('.bible-verse-action').first().click();
  await page.getByRole('button', { name: 'Guardar favorito', exact: true }).click();
  await page.getByText('No se pudo guardar en este dispositivo.').waitFor();
  assert.equal(await page.getByRole('button', { name: 'Guardar favorito', exact: true }).getAttribute('aria-pressed'), 'false');
  const offlineContext = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  await offlineContext.route('https://**/*', route => route.abort());
  const offlinePage = await offlineContext.newPage();
  offlinePage.on('pageerror', error => errors.push(error.message));
  await offlinePage.goto(`${base}/biblia`);
  await offlinePage.locator('.bible-verse-action').first().waitFor();
  await offlinePage.getByLabel('Descargas', { exact: true }).click();
  for (const id of ['RVR1960', 'NTV', 'NVI']) {
    await offlinePage.getByLabel(`Descargar ${id}`, { exact: true }).click();
    await offlinePage.getByLabel(`Eliminar descarga de ${id}`, { exact: true }).waitFor({ timeout: 60000 });
  }
  await offlinePage.getByRole('dialog').getByLabel('Cerrar ventana').click();
  await offlinePage.evaluate(async () => { await navigator.serviceWorker.ready; });
  await offlinePage.reload();
  await offlinePage.locator('.bible-verse-action').first().waitFor();
  await offlineContext.setOffline(true);
  await offlinePage.goto(`${base}/biblia?version=RVR1960&book=JHN&chapter=3`);
  await offlinePage.locator('.bible-verse-action').first().waitFor();
  await offlinePage.getByLabel('Comparar versiones', { exact: true }).click();
  await offlinePage.getByRole('button', { name: 'Comparar', exact: true }).click();
  for (const id of ['RVR1960', 'NTV', 'NVI']) await offlinePage.getByRole('region', { name: `Lectura ${id}`, exact: true }).locator('.bible-verse-action').first().waitFor();
  await offlinePage.screenshot({ path: `${output}/compare-offline.png` });
  await offlinePage.getByLabel('Comparar versiones', { exact: true }).click();
  await offlinePage.getByRole('checkbox', { name: /NVI/ }).uncheck();
  await offlinePage.getByRole('checkbox', { name: /TLA/ }).check();
  await offlinePage.getByRole('button', { name: 'Comparar', exact: true }).click();
  await offlinePage.getByRole('region', { name: 'Lectura TLA', exact: true }).getByRole('alert').waitFor();
  assert.ok(await offlinePage.getByRole('region', { name: 'Lectura NTV', exact: true }).locator('.bible-verse-action').count() > 0);
  await offlineContext.close();
  await page.getByLabel('Cerrar selección').click();
  await page.getByLabel('Salir de la Biblia').click();
  await page.getByRole('navigation', { name: 'Navegación móvil' }).waitFor();
  assert.equal(await page.locator('.bible-immersive').count(), 0);
  assert.notEqual(await page.evaluate(() => getComputedStyle(document.body).overflow), 'hidden');
  assert.deepEqual(errors, []);
  console.log('PASS: separate verses, copy/citation, favorites persist and jump, synchronized comparison, visible stacked mobile panels, two/three versions, chapter changes, version-scoped favorites, clipboard denial, storage failure and offline comparison with per-column errors.');
} finally { await browser.close(); }
