import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import process from 'node:process';
const { chromium } = createRequire(import.meta.url)('playwright');
const base = process.env.BIBLE_TEST_URL || 'http://127.0.0.1:5181';
const output = 'test-results/bible-customization';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
try {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, reducedMotion: 'reduce' });
  await context.route('https://**/*', route => route.abort());
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}/biblia?version=RVR1960&book=PSA&chapter=23`);
  const verse = page.locator('.bible-verse-start[data-reference="PSA.23.1"]');
  await verse.waitFor();
  const box = await verse.boundingBox();
  await page.touchscreen.tap(box.x + 60, box.y + 15);
  await page.getByLabel('Copiar versículo', { exact: true }).waitFor();
  assert.equal(await page.getByRole('dialog').count(), 0);
  assert.ok(await verse.evaluate(element => element.classList.contains('bible-verse-selected')));
  await page.getByLabel('Guardar favorito', { exact: true }).click();
  await page.screenshot({ path: `${output}/selected-mobile.png` });
  await page.getByLabel('Cerrar selección', { exact: true }).click();
  await page.getByLabel('Opciones del versículo PSA.23.1', { exact: true }).focus();
  await page.keyboard.press('Enter');
  await page.getByLabel('Copiar versículo', { exact: true }).waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await page.getByLabel('Copiar versículo', { exact: true }).count(), 0);
  await page.getByLabel('Ajustes de lectura').click();
  await page.getByRole('button', { name: 'Fondos por versión', exact: true }).click();
  await page.getByLabel('Fondo Rosa para RVR1960').click();
  assert.equal(await page.getByLabel('Fondo Rosa para RVR1960').getAttribute('aria-pressed'), 'true');
  await page.screenshot({ path: `${output}/background-settings.png` });
  await page.getByRole('dialog').getByLabel('Cerrar ventana').click();
  await page.getByRole('dialog').getByLabel('Cerrar ventana').click();
  await page.reload();
  await verse.waitFor();
  assert.equal(await page.locator('article').getAttribute('data-background'), 'rose');
  await page.getByLabel('Comparar versiones', { exact: true }).click();
  await page.getByRole('button', { name: 'Comparar', exact: true }).click();
  await page.getByRole('region', { name: 'Lectura NVI', exact: true }).locator('.bible-verse-start').first().waitFor();
  const backgrounds = await page.locator('.bible-compare-column').evaluateAll(elements => elements.map(element => getComputedStyle(element).backgroundColor));
  assert.equal(new Set(backgrounds).size, 3);
  await page.screenshot({ path: `${output}/compare-colors-mobile.png` });
  await page.getByLabel('Cerrar versión RVR1960', { exact: true }).click();
  assert.equal(await page.locator('.bible-compare-column').count(), 2);
  await page.getByRole('region', { name: 'Lectura NTV', exact: true }).getByLabel('Opciones del versículo PSA.23.1', { exact: true }).click();
  assert.equal(await page.getByRole('region', { name: 'Lectura NVI', exact: true }).locator('.bible-verse-selected').count(), 0);
  await page.setViewportSize({ width: 320, height: 568 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: `${output}/selected-short-mobile.png` });
  await page.getByLabel('Cerrar versión NTV', { exact: true }).click();
  await verse.waitFor();
  assert.equal(await page.locator('.bible-compare-column').count(), 0);
  assert.equal(await page.getByLabel('Versión de la Biblia').inputValue(), 'RVR1960');
  assert.equal(await page.getByLabel('Copiar versículo', { exact: true }).count(), 0);
  assert.equal(new URL(page.url()).searchParams.get('chapter'), '23');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByLabel('Comparar versiones', { exact: true }).click();
  await page.getByRole('button', { name: 'Comparar', exact: true }).click();
  await page.getByRole('region', { name: 'Lectura NVI', exact: true }).locator('.bible-verse-start').first().waitFor();
  await page.getByLabel('Ajustes de lectura').click();
  await page.getByLabel('Tema claro').click();
  await page.getByRole('dialog').getByLabel('Cerrar ventana').click();
  await page.screenshot({ path: `${output}/compare-colors-desktop.png` });
  await page.getByLabel('Cerrar versión NVI', { exact: true }).click();
  assert.equal(await page.locator('.bible-compare-column').count(), 2);
  await page.getByLabel('Cerrar versión NTV', { exact: true }).click();
  await verse.waitFor();
  assert.equal(await page.getByLabel('Versión de la Biblia').inputValue(), 'RVR1960');
  await page.getByLabel('Versión de la Biblia').selectOption('NTV');
  await page.locator('article .bible-verse-start').first().waitFor();
  await page.getByLabel('Comparar versiones', { exact: true }).click();
  await page.getByRole('button', { name: 'Comparar', exact: true }).click();
  await page.getByLabel('Cerrar versión NTV', { exact: true }).click();
  await page.getByLabel('Cerrar versión NVI', { exact: true }).click();
  await page.locator('article .bible-verse-start').first().waitFor();
  assert.equal(await page.getByLabel('Versión de la Biblia').inputValue(), 'NTV', 'Restore the actual pre-comparison version');
  assert.deepEqual(errors, []);
  console.log('PASS: touch/keyboard selection without modal, version-specific highlighting, custom background persistence, light/dark palettes, close primary/secondary panels, 3-to-2-to-single reading and compact mobile actions.');
} finally { await browser.close(); }
