import { createRequire } from 'node:module';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = createRequire(import.meta.url)('@electric-sql/pglite');
const db = new PGlite();
const alice = '10000000-0000-0000-0000-000000000001', bob = '10000000-0000-0000-0000-000000000002';
const entry = n => ({ version: 'RVR1960', book: 'PSA', chapter: 23, reference: `PSA.23.${n}`, label: String(n), title: 'Salmos', text: `Texto ${n}` });
let sequence = 0;
const op = (n, remove = false) => ({ id: `20000000-0000-0000-0000-${String(++sequence).padStart(12, '0')}`, key: `RVR1960:PSA.23.${n}`, entry: remove ? null : entry(n) });
const rpc = async ops => (await db.query('select public.sync_bible_favorites($1::jsonb) as value', [JSON.stringify(ops)])).rows[0].value;
const as = async (role, user = '') => { await db.exec(`reset role; set role ${role};`); await db.query("select set_config('request.jwt.claim.sub',$1,false)", [user]); };
try {
  await db.exec(`create role anon; create role authenticated; create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid$$;
    grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;`);
  await db.query('insert into auth.users values($1),($2)', [alice, bob]);
  const sql = await readFile(new URL('../supabase/migrations/202610100001_bible_favorites.sql', import.meta.url), 'utf8');
  await db.exec(sql); await db.exec(sql);
  await as('anon'); await assert.rejects(rpc([]), e => e.code === '42501');
  await as('authenticated'); await assert.rejects(rpc([]), e => e.code === '42501');
  await as('authenticated', alice);
  const add = op(1), initial = await rpc([add]);
  assert.equal(initial.favorites.length, 1);
  assert.equal((await rpc([add])).revision, initial.revision, 'retry is idempotent');
  const deleted = await rpc([op(1, true)]);
  assert.equal(deleted.favorites.length, 0); assert.ok(deleted.revision > initial.revision);
  assert.equal((await rpc([add])).favorites.length, 0, 'old save retry cannot resurrect deletion');
  await assert.rejects(rpc([{ ...add, entry: entry(2) }]), e => e.code === '22023');
  const next = op(2); await rpc([next]);
  await assert.rejects(db.query('delete from public.bible_favorites'), e => e.code === '42501');
  await assert.rejects(db.query('select * from public.bible_favorite_operations'), e => e.code === '42501');
  await as('authenticated', bob);
  assert.equal((await rpc([])).favorites.length, 0);
  assert.equal((await db.query('select * from public.bible_favorites')).rows.length, 0, 'RLS blocks another account');
  const invalid = op(3); invalid.entry.reference = 'PSA.23.3+MAT.23.4'; invalid.key = `RVR1960:${invalid.entry.reference}`;
  await assert.rejects(rpc([op(1), invalid]), e => e.code === '22023');
  assert.equal((await rpc([])).favorites.length, 0, 'invalid batch rolls back all writes');
  await assert.rejects(rpc([{ ...op(1), user_id: alice }]), e => e.code === '22023');
  await assert.rejects(rpc(Array.from({ length: 51 }, (_, i) => op(i + 1))), e => e.code === '22023');
  for (let i = 0; i < 10; i++) await rpc(Array.from({ length: 50 }, (_, n) => op(i * 50 + n + 1)));
  assert.equal((await rpc([])).favorites.length, 500);
  await assert.rejects(rpc([op(501)]), e => e.code === '22023');
  assert.equal((await rpc([op(1, true), op(501)])).favorites.length, 500);
  console.log('PASS: repeatable migration, RLS/account isolation, authentication, validation, atomic batches, quota, monotonic revisions, idempotency including delete/retry.');
} finally { await db.close(); }
