import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import process from 'node:process';
const { chromium } = createRequire(import.meta.url)('playwright');
const base = process.env.BIBLE_TEST_URL || 'http://127.0.0.1:5181';
const output = 'test-results/bible-experience';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', permissions: ['clipboard-read', 'clipboard-write'] });
  await context.route('https://**/*', route => route.abort());
  const page = await context.newPage();
  page.setDefaultTimeout(15000);
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}/biblia`);
  await page.getByLabel('Opciones del versículo GEN.1.1', { exact: true }).waitFor();
  const first = await page.locator('.bible-verse-start[data-reference="GEN.1.1"]').boundingBox();
  const second = await page.locator('.bible-verse-start[data-reference="GEN.1.2"]').boundingBox();
  assert.ok(second.y >= first.y + first.height, 'Verses must occupy separate lines');
  await page.getByLabel('Opciones del versículo GEN.1.1', { exact: true }).click();
  await page.getByRole('button', { name: 'Guardar favorito', exact: true }).click();
  await page.getByRole('button', { name: 'Copiar versículo', exact: true }).click();
  await page.getByText('Versículo copiado con su referencia.').waitFor();
  assert.equal((await page.evaluate(() => navigator.clipboard.readText())).replace(/\r\n/g, '\n'), 'En el principio creó Dios los cielos y la tierra.\n\nGénesis 1:1 (RVR1960)');
  await page.screenshot({ path: `${output}/verse-actions.png` });
  await page.getByRole('dialog').getByLabel('Cerrar ventana').click();
  await page.reload();
  await page.getByLabel('Marcadores', { exact: true }).click();
  await page.getByRole('tab', { name: /Versículos/ }).click();
  assert.match(await page.getByRole('tabpanel').innerText(), /Génesis 1:1 \(RVR1960\)/);
  await page.locator('.bible-favorite-row > button').first().click();
  await page.locator('.bible-verse-selected[data-reference="GEN.1.1"]').waitFor();
  await page.getByLabel('Comparar versiones', { exact: true }).click();
  assert.equal(await page.getByRole('checkbox').count(), 4);
  assert.equal(await page.getByRole('checkbox').last().isDisabled(), true);
  await page.getByRole('button', { name: 'Comparar', exact: true }).click();
  await page.getByRole('region', { name: 'Lectura NVI', exact: true }).locator('.bible-verse-action').first().waitFor();
  const regions = page.locator('.bible-compare-scroll');
  assert.equal(await regions.count(), 3);
  await regions.nth(0).evaluate(element => { element.scrollTop = 400; });
  let scrolls = await regions.evaluateAll(elements => elements.map(element => element.scrollTop));
  assert.deepEqual(scrolls, [400, 0, 0]);
  await regions.nth(1).evaluate(element => { element.scrollTop = 220; });
  scrolls = await regions.evaluateAll(elements => elements.map(element => element.scrollTop));
  assert.deepEqual(scrolls, [400, 220, 0]);
  await page.screenshot({ path: `${output}/compare-desktop.png` });
  await page.getByRole('region', { name: 'Lectura NVI', exact: true }).getByLabel('Opciones del versículo GEN.1.1', { exact: true }).click();
  assert.match(await page.getByRole('dialog').innerText(), /Génesis 1:1 \(NVI\)/);
  await page.getByRole('button', { name: 'Guardar favorito', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Cerrar ventana').click();
  for (const width of [320, 390, 768]) {
    await page.setViewportSize({ width, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${width}`);
    const tabs = page.getByRole('navigation', { name: 'Versiones en comparación' });
    await tabs.getByRole('button', { name: 'NTV', exact: true }).click();
    await page.waitForFunction(() => Math.abs(document.querySelector('.bible-compare-track').scrollLeft - document.querySelector('.bible-compare-track').clientWidth) < 2);
    assert.ok((await regions.nth(0).evaluate(element => element.scrollTop)) > 0, 'Switching columns must preserve scroll');
    await page.screenshot({ path: `${output}/compare-${width}.png` });
  }
  await page.getByRole('button', { name: 'Siguiente', exact: true }).click();
  await page.getByRole('region', { name: 'Lectura NVI', exact: true }).locator('.bible-verse-action').first().waitFor();
  assert.deepEqual(await regions.evaluateAll(elements => elements.map(element => element.scrollTop)), [0, 0, 0]);
  assert.ok((await page.locator('.bible-compare-column > header').allTextContents()).every(text => text.includes('2')));
  await page.getByLabel('Cerrar comparación').click();
  await page.getByLabel('Marcadores', { exact: true }).click();
  assert.equal(await page.locator('.bible-favorite-row').count(), 2);
  await page.getByLabel('Eliminar favorito Génesis 1:1 (NVI)', { exact: true }).click();
  assert.equal(await page.locator('.bible-favorite-row').count(), 1);
  await page.getByRole('dialog').getByLabel('Cerrar ventana').click();
  // Permission denial must provide selectable text instead of claiming a successful copy.
  await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw new DOMException('Denied', 'NotAllowedError'); }; });
  await page.locator('.bible-verse-action').first().click();
  await page.getByRole('button', { name: 'Copiar versículo', exact: true }).click();
  await page.getByLabel('Texto para copiar').waitFor();
  assert.ok((await page.getByLabel('Texto para copiar').inputValue()).includes('(RVR1960)'));
  await page.getByRole('dialog').getByLabel('Cerrar ventana').click();
  // Storage failure must not pretend that a favorite was persisted.
  await page.evaluate(() => { const original = Storage.prototype.setItem; Storage.prototype.setItem = function (key, value) { if (key === 'bible:verseFavorites') throw new DOMException('Full', 'QuotaExceededError'); return original.call(this, key, value); }; });
  await page.locator('.bible-verse-action').first().click();
  await page.getByRole('button', { name: 'Guardar favorito', exact: true }).click();
  await page.getByText('No se pudo guardar en este dispositivo.').waitFor();
  assert.equal(await page.getByRole('button', { name: 'Guardar favorito', exact: true }).getAttribute('aria-pressed'), 'false');
  const offlineContext = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  await offlineContext.route('https://**/*', route => route.abort());
  const offlinePage = await offlineContext.newPage();
  offlinePage.on('pageerror', error => errors.push(error.message));
  await offlinePage.goto(`${base}/biblia`);
  await offlinePage.locator('.bible-verse-action').first().waitFor();
  await offlinePage.getByLabel('Descargas', { exact: true }).click();
  for (const id of ['RVR1960', 'NTV', 'NVI']) {
    await offlinePage.getByLabel(`Descargar ${id}`, { exact: true }).click();
    await offlinePage.getByLabel(`Eliminar descarga de ${id}`, { exact: true }).waitFor({ timeout: 60000 });
  }
  await offlinePage.getByRole('dialog').getByLabel('Cerrar ventana').click();
  await offlinePage.evaluate(async () => { await navigator.serviceWorker.ready; });
  await offlinePage.reload();
  await offlinePage.locator('.bible-verse-action').first().waitFor();
  await offlineContext.setOffline(true);
  await offlinePage.goto(`${base}/biblia?version=RVR1960&book=JHN&chapter=3`);
  await offlinePage.locator('.bible-verse-action').first().waitFor();
  await offlinePage.getByLabel('Comparar versiones', { exact: true }).click();
  await offlinePage.getByRole('button', { name: 'Comparar', exact: true }).click();
  for (const id of ['RVR1960', 'NTV', 'NVI']) await offlinePage.getByRole('region', { name: `Lectura ${id}`, exact: true }).locator('.bible-verse-action').first().waitFor();
  await offlinePage.screenshot({ path: `${output}/compare-offline.png` });
  await offlinePage.getByLabel('Comparar versiones', { exact: true }).click();
  await offlinePage.getByRole('checkbox', { name: /NVI/ }).uncheck();
  await offlinePage.getByRole('checkbox', { name: /TLA/ }).check();
  await offlinePage.getByRole('button', { name: 'Comparar', exact: true }).click();
  await offlinePage.getByRole('region', { name: 'Lectura TLA', exact: true }).getByRole('alert').waitFor();
  assert.ok(await offlinePage.getByRole('region', { name: 'Lectura NTV', exact: true }).locator('.bible-verse-action').count() > 0);
  await offlineContext.close();
  assert.deepEqual(errors, []);
  console.log('PASS: separate verses, copy/citation, favorites persist and jump, independent comparison scroll, responsive tabs, chapter changes, version-scoped favorites, clipboard denial, storage failure and offline comparison with per-column errors.');
} finally { await browser.close(); }
