import { createRequire } from 'node:module';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = createRequire(import.meta.url)('@electric-sql/pglite');
const db = new PGlite();
const user = '00000000-0000-0000-0000-000000000001';
const other = '00000000-0000-0000-0000-000000000002';
const lesson = n => `10000000-0000-0000-0000-${String(n).padStart(12, '0')}`;
const content = ['Jn 1:1', 'Texto', 'Ensenanza', [{ text: 'Pregunta' }, { text: '' }, { text: 'Opcional', required: false }]];
const asUser = async id => { await db.exec('reset role; set role authenticated;'); await db.query("select set_config('request.jwt.claim.sub', $1, false)", [id]); };
const save = async (n, answers = { 0: 'Respuesta' }, revision = content) => (await db.query('select public.complete_study_lesson($1,$2,$3) as result', [lesson(n), JSON.stringify(answers), JSON.stringify(revision)])).rows[0].result;
const status = async () => (await db.query('select public.get_study_status() as result')).rows[0].result;
try {
  await db.exec(`
    create role anon; create role authenticated; create schema auth;
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid$$;
    create table public.profiles(id uuid primary key, full_name text, church_name text, avatar_url text, role text);
    create table public.study_weeks(id uuid primary key, plan_id uuid);
    create table public.study_lessons(id uuid primary key, week_id uuid, scripture_ref text, scripture_text text, teaching text, questions jsonb);
    create table public.user_progress(user_id uuid, lesson_id uuid references public.study_lessons(id), completed boolean, answers jsonb, completed_at timestamptz, unique(user_id,lesson_id));
    create table public.user_streaks(user_id uuid primary key, current_streak integer, max_streak integer, total_xp integer, last_study_date timestamptz);
    create table public.notifications(id uuid default gen_random_uuid(), user_id uuid, title text, message text, type text, action_url text);
    grant all on public.user_progress, public.user_streaks to authenticated;
    grant update(current_streak) on public.user_streaks to authenticated;
  `);
  for (let i = 1; i <= 45; i++) await db.query('insert into public.study_lessons(id, scripture_ref, scripture_text, teaching, questions) values($1,$2,$3,$4,$5)', [lesson(i), ...content.slice(0, 3), JSON.stringify(content[3])]);
  const migration = await readFile(new URL('../supabase/migrations/202610050001_atomic_study.sql', import.meta.url), 'utf8');
  await db.exec(migration);
  await db.exec(migration);
  await db.exec('set role anon;');
  await assert.rejects(status(), e => e.code === '42501');
  await assert.rejects(save(1), e => e.code === '42501');
  await asUser(user);
  assert.equal((await status()).current_streak, 0);
  await assert.rejects(db.query('select public.study_streak_summary($1, now())', [other]), e => e.code === '42501');
  await assert.rejects(save(1, {}), /preguntas pendientes/);
  await assert.rejects(save(1, { 0: 123 }), /preguntas pendientes/);
  await assert.rejects(save(1, { 0: '   ' }), /preguntas pendientes/);
  await assert.rejects(save(1, { 0: '\n\t\r' }), /preguntas pendientes/);
  await assert.rejects(save(1, {}, []), e => e.code === 'P0002');
  const first = await save(1);
  assert.equal(first.status.current_streak, 1);
  assert.equal(first.added_xp, 10);
  assert.equal(first.status.today_completed, true);
  assert.equal(first.status.recent_days.length, 7);
  const repeat = await save(1, { 0: 'Replacement' });
  assert.equal(repeat.already_completed, true);
  assert.equal(repeat.status.total_xp, 10);
  assert.equal((await save(2)).status.current_streak, 1);
  await assert.rejects(db.query('update public.user_streaks set current_streak = 999'), e => e.code === '42501');
  await assert.rejects(db.query('delete from public.user_progress'), e => e.code === '42501');
  await assert.rejects(db.query('truncate public.user_progress'), e => e.code === '42501');
  await assert.rejects(db.query("insert into public.user_progress values($1,$2,true,'{}',now())", [user, lesson(3)]), e => e.code === '42501');
  await asUser(other);
  assert.equal((await status()).current_streak, 0);
  await db.exec('reset role;');
  assert.equal((await db.query('select answers from public.user_progress where user_id=$1 and lesson_id=$2', [user, lesson(1)])).rows[0].answers[0], 'Respuesta');
  // Existing completions repair a stale zero counter without rewriting history or XP.
  for (let i = 1; i <= 6; i++) await db.query("insert into public.user_progress values($1,$2,true,'{}',((now() at time zone 'America/La_Paz')::date - $3::integer + time '12:00') at time zone 'America/La_Paz')", [other, lesson(i), i]);
  await asUser(other);
  assert.equal((await status()).current_streak, 6);
  const seven = await save(7);
  assert.equal(seven.status.current_streak, 7);
  assert.equal(seven.added_xp, 30);
  assert.equal((await save(7)).added_xp, 0);
  assert.equal((await save(8)).added_xp, 10);
  await db.exec('reset role;');
  assert.equal((await db.query('select count(*)::integer as n from public.notifications')).rows[0].n, 1);
  // Failure after the progress insert rolls back the entire save and remains retryable.
  await db.exec(`create function public.test_fail_streak() returns trigger language plpgsql as $$begin raise exception 'Simulated failure'; end;$$;
    create trigger test_fail before insert or update on public.user_streaks for each row execute function public.test_fail_streak();`);
  await asUser(user);
  await assert.rejects(save(9), /Simulated failure/);
  await db.exec('reset role;');
  assert.equal((await db.query('select count(*)::integer as n from public.user_progress where lesson_id=$1', [lesson(9)])).rows[0].n, 0);
  await db.exec('drop trigger test_fail on public.user_streaks;');
  await asUser(user);
  assert.equal((await save(9)).added_xp, 10);
  await db.exec('reset role;');
  // Fixed weekend + midnight dates exercise the production projection, not a JS copy.
  await db.query('delete from public.user_progress where user_id=$1', [other]);
  for (const [n, date] of [[1, '2026-10-03T18:00:00Z'], [2, '2026-10-04T18:00:00Z']]) await db.query("insert into public.user_progress values($1,$2,true,'{}',$3)", [other, lesson(n), date]);
  const at = async time => (await db.query('select public.study_streak_summary($1,$2) as result', [other, time])).rows[0].result;
  assert.equal((await at('2026-10-05T03:59:00Z')).current_streak, 2);
  assert.equal((await at('2026-10-05T04:01:00Z')).current_streak, 2);
  assert.equal((await at('2026-10-06T04:01:00Z')).current_streak, 0);
  assert.equal((await at('2026-10-03T19:00:00Z')).current_streak, 1, 'future rows excluded');
  await db.query('delete from public.user_progress where user_id=$1', [other]);
  for (let i = 1; i <= 29; i++) await db.query("insert into public.user_progress values($1,$2,true,'{}',((now() at time zone 'America/La_Paz')::date - $3::integer + time '12:00') at time zone 'America/La_Paz')", [other, lesson(i), i]);
  await asUser(other);
  const thirty = await save(30);
  assert.equal(thirty.status.current_streak, 30);
  assert.equal(thirty.added_xp, 110);
  assert.equal((await save(30)).added_xp, 0);
  assert.equal((await save(31)).added_xp, 10);
  const xp = (await status()).total_xp;
  const retries = await Promise.all(Array.from({ length: 20 }, () => save(31)));
  assert.ok(retries.every(result => result.already_completed && result.added_xp === 0));
  assert.equal((await status()).total_xp, xp);
  console.log('PASS SQL: atomic rollback/retry, idempotency, same-day XP, history-derived streaks, weekend/midnight, server dates, input validation, migration rerun, anonymous/other-user/direct-write protection and bonus once. Isolated fixture, not production.');
} finally { await db.close(); }
